version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
    commands:
      - dotnet tool install -g Amazon.Lambda.Tools
  
  pre_build:
    commands:
      - echo Restore started on `date`
      - cd service-availability-function
      - dotnet clean
      - dotnet restore
      
  build:
    commands:
      - echo Build started on `date`
      - echo KMS KEY - $CODEBUILD_KMS_KEY
      - dotnet lambda package-ci --kms-key $CODEBUILD_KMS_KEY --configuration Release --framework netcoreapp3.1 --s3-bucket $BUCKET --template service-availability-function.template --output-template bin/Release/netcoreapp3.1/$PROJECT_NAME.template --output-package bin/Release/netcoreapp3.1/$PROJECT_NAME.zip

artifacts:
  name: BuildOutput
  files:
    - service-availability-function/bin/Release/netcoreapp3.1/$PROJECT_NAME.template
  discard-paths: yes  